<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxUqh8K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxUqh8K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxUqh8K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxUqh8K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxUqh8K\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxUqh8K',
    'container.build_id' => 'a1b8ce82',
    'container.build_time' => 1618864220,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxUqh8K');
