<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFG7XO1U\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFG7XO1U/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFG7XO1U.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFG7XO1U\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFG7XO1U\App_KernelDevDebugContainer([
    'container.build_hash' => 'FG7XO1U',
    'container.build_id' => 'e0c860a3',
    'container.build_time' => 1620325966,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFG7XO1U');
