<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYdtnqB6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYdtnqB6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYdtnqB6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYdtnqB6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYdtnqB6\App_KernelDevDebugContainer([
    'container.build_hash' => 'YdtnqB6',
    'container.build_id' => '9d26341d',
    'container.build_time' => 1620322860,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYdtnqB6');
